### ISSUE TITLE
Battery of Totems bug

### ISSUE THREAD

**Issue by xMikux** [Apeiros-46B/AlchimiaVitae#2]
## Description (Required)
There have two bug on this infusion.

1. It can add more than 8 totems of undying
2. You can put not totems of undying when you put one totems of undying on offhand.

## Steps to reproduce the Issue (Required)

More than 8 totems of undying
1. Add 8 totems of undying and add one more.

 Not totems of undying item
1. Put totems of undying on offhand
2. Main hand take other type (not totems of undying)
3. And you will see it can fake the totems of undying, only cost other type in main hand items.

## Expected behavior (Required)

1. Can't put more than 8 totems of undying.

2. Can't put other not totems of undying item in.

## Server Log / Error Report
N/A

## Environment (Required)
![image](https://user-images.githubusercontent.com/26039249/125831857-3f6b58bd-930b-4a83-9748-ca9ac8a42738.png)

 - Minecraft Version: git-Paper-782 (MC: 1.16.5)
 - Slimefun Version: DEV - 949 (git 6392af00)
 - Plugin Version: vDEV - 6 (git ed96769e)

**Comment by xMikux** [comment]
hmm, it look like it won't cost any totems of undying on offhand ,  i only put totems of undying on offhand, and main hand don't take anything, still will add, and offhand totems of undying didn't cost it.

**Comment by Apeiros-46B** [comment]
my computer broke, im still working on installing the stuff i need to work on the addon because i reinstalled my system to fix issues, although i should be able to fix this soon
