### ISSUE TITLE
Can't create

### ISSUE THREAD

**Issue by 100petr** [Apeiros-46B/AlchimiaVitae#4]
## Description (Required)

Can't create Altar of Infusion
## Steps to reproduce the Issue (Required)

Put in Divine altar recipe
Click on the craft
Look at the chat
![image](https://user-images.githubusercontent.com/29830635/155835172-b3bbc875-06d5-4041-a38b-900611f8c6c9.png)
![image](https://user-images.githubusercontent.com/29830635/155835180-741652ad-3b5d-44e2-8159-f0f74a501c9e.png)
![image](https://user-images.githubusercontent.com/29830635/155835188-8dc1050e-929d-406b-b783-cb71dcd8316c.png)
(number of NBT tags is same)
## Expected behavior (Required)

Creation of Altar of Infusion will be possible
## Server Log / Error Report

N/A
## Environment (Required)

 - Minecraft Version: 1.18.1 (purpur)
 - CS-CoreLib Version: N/A
 - Slimefun Version: DEV 999
 - Plugin Version: DEV 18

**Comment by 100petr** [comment]
Ornate Cauldron the player finally managed to do, deleted from the issue, now the production of potion of osmosis does not work. There will probably be more problems with divine altar.

**Comment by Apeiros-46B** [comment]
Can you do `/sf versions`?

**Comment by 100petr** [comment]
Ok, it works, I have no idea what the problem was before. Maybe the player had a blistering ingot of 66%. Another thing that players fail to produce is potion of osmosis. There is perhaps nothing to confuse in this recipe. It writes an invalid recipe

**Comment by RIPISDRAD** [comment]
hey all
I got the same issue
and if u pay attention
there is a different between what u said to put it in and what it is that we actually have
and nbt tags is 3 for one that we have to craft in it and the one that we make is 2 and the lores are different!
btw why wouldn't u answer discord?

**Comment by RIPISDRAD** [comment]
and as it seems the exp crystals got an issue that they don't merg!
this is how I fixed it! (I got a similar problem like this so by chance it fixed)
the problems is like that all this happens cause u log out and log in! like the item before log out is different with after the time u logged in!
so yea and I placed one of the alters down and then test it I was right it was fixed! lol

**Comment by Apeiros-46B** [comment]
> there is a different between what u said to put it in and what it is that we actually have
and nbt tags is 3 for one that we have to craft in it and the one that we make is 2 and the lores are different!

@RIPISDRAD can you do `/paper dumpitem` for each item and send them all in a pastebin? (You can copy the text from console) 
Experience crystals are also stacking like normal for me:

https://user-images.githubusercontent.com/61390942/156865144-76ace32c-abb3-4bf5-8043-2a9756d28d42.mp4

Also, @100petr, I just tried it and potion of osmosis crafting worked perfectly fine for me. Can you try to reproduce it again?

https://user-images.githubusercontent.com/61390942/156864656-d6d2f5ec-b55e-4a67-b5e0-47c6ed6259ab.mp4

Relevant plugin and java versions that I used:
![image](https://user-images.githubusercontent.com/61390942/156864717-ef42f18b-6c02-4901-975c-53ca0e7e39de.png)
![image](https://user-images.githubusercontent.com/61390942/156864727-5907dd16-0f04-4251-86ae-15b5726b6a94.png)
![image](https://user-images.githubusercontent.com/61390942/156864733-8c941af1-5cef-47c5-be19-3c41631d7387.png)

**Comment by 100petr** [comment]
the player has a recipe ready for Ornate Cauldron that doesn't work for him. I tried to put the items through sf give and everything except the experience crysta could be combined. So there must be a problem with them. 
unfunctional - https://pastebin.com/wn8sKNzd somehow there is additional HideFlags
functional - https://pastebin.com/E4uaa2RN

**Comment by Apeiros-46B** [comment]
Can you send screenshots of both of the crystals?

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/156914593-cb472f0b-7de3-4fd8-8c4e-dd1683942699.png)
Um, those who can't be used have Crysta in their name

**Comment by 100petr** [comment]
I probably wouldn't deal with it anymore, when during production (at least what I tried) it's OK. I'll let the players know if they can't do something, let me know and I will contact you depending on situation. If I knew at the beginning that there was a mistake in the name, I would just exchange it for the player. I thought there was a problem with the machine. If @RIPISDRAD will not write anything in a few days, I will close the issue. Thank you for your time

**Comment by Apeiros-46B** [comment]
I've figured out the cause and I'm working on a fix. It should be done by the end of tomorrow, although I can't guarantee it won't be delayed (I'm pretty busy currently)

**Comment by RIPISDRAD** [comment]
Ok man hope u fixed it
I really cant tell much cause i can't play too 😭 so yea it depends on
people to report it
But nice to see uve fixed it
