### ISSUE TITLE
caught this in my console upon startup. not sure what it is

### ISSUE THREAD

**Issue by Boomer-1** [Apeiros-46B/AlchimiaVitae#6]
## Description (Required)

see pastebin
https://pastebin.com/sKwS62z1

## Environment (Required)

 - Minecraft Version:1.18.1
 - CS-CoreLib Version:n/a
 - Slimefun Version: 1006
 - Plugin Version: 19

**Comment by Apeiros-46B** [comment]
AlchimiaVitae requires 1.18.2 now, due to a change in Paper.
I might make a legacy version later though (for Spigot 1.16.x-1.18.x or Paper < 1.18.2)
