### ISSUE TITLE
Invalid recipe error when trying to craft Potion of Osmosis

### ISSUE THREAD

**Issue by Jota-byte** [Apeiros-46B/AlchimiaVitae#7]
## Description (Required)
What the title says. It's not possible to craft the Potion of Osmosis, it keeps saying you have an invalid recipe even when you got the correct items in the correct order.

## Steps to reproduce the Issue (Required)
1. Get all the items from the recipe
2. Get a Divine Alter and place it
3. Put the items in the input slots from the altar in the correct order
4. Get the message "That recipe is invalid! Please try again"
Video:
https://user-images.githubusercontent.com/83108504/205981096-476f1732-42aa-4ef5-8c20-b110ea6a17d1.mp4

## Expected behavior (Required)
To get the Potion of Osmosis

## Server Log / Error Report
No errors in the console

## Environment (Required)
 - Minecraft Version: Paper git-Paper-81 (MC: 1.19)
 - CS-CoreLib Version: Not installed
 - Slimefun Version: Slimefun DEV - 1035 (git 0b7c656d)
 - Plugin Version: AlchimiaVitae vDEV - 22 (git 09618c12)

**Comment by Apeiros-46B** [comment]
Should be fixed in the latest build (just pushed the commit, wait a bit for the build to release)
Sorry for the delay, I was also cleaning up and rewriting a bunch of other stuff so I didn't get to this first
